# Phase 2 — Baseline Models

### Importing Libraries

In [51]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
from sklearn.preprocessing import StandardScaler


### Loading the Dataset

In [52]:
# loading data
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("val.csv")
test_df = pd.read_csv("test.csv")

# takeing a peak at data 
train_df.head()

# turning them into matreses 
X_train = train_df[[f"p{i}" for i in range(1, 43)] + ["turn"]].values.astype("int")
y_train = train_df["label_move_col"].values.astype("int")

X_val = val_df[[f"p{i}" for i in range(1, 43)] + ["turn"]].values.astype("int")
y_val = val_df["label_move_col"].values.astype("int")

X_test = test_df[[f"p{i}" for i in range(1, 43)] + ["turn"]].values.astype("int")



### Standardization of Features

In [53]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.fit_transform(X_test)

train_df["label_move_col"].value_counts().sort_index()

label_move_col
0     7136
1     4111
2     4923
3    17653
4     4923
5     4111
6     7136
Name: count, dtype: int64

# Logistic Regression Model
### Training and Evaluation

In [54]:
# training logistic regression

Logistic_regression_model =  LogisticRegression(max_iter = 3000 , solver ="lbfgs" ,class_weight="balanced" , C=1 ,random_state=42 )

Logistic_regression_model.fit(X_train_scaled , y_train)

# predict on validation data
y_val_pred = Logistic_regression_model.predict(X_val_scaled)

#accuracy
val_acc = accuracy_score(y_val , y_val_pred)
print("validation accuracy: ", val_acc)

# confusion matrix
print("\nconfusion matrix: \n", confusion_matrix(y_val , y_val_pred))
print("\n\nclassification report: \n", classification_report(y_val , y_val_pred , digits =3))

validation accuracy:  0.17672173751624282

confusion matrix: 
 [[194 208 259 185 249 219 136]
 [ 83 207 169  85 133 148 100]
 [ 90 133 281 123 175 137  94]
 [364 575 769 542 769 575 364]
 [ 94 137 175 123 281 133  90]
 [100 148 133  85 169 207  83]
 [138 219 249 185 259 208 192]]


classification report: 
               precision    recall  f1-score   support

           0      0.183     0.134     0.154      1450
           1      0.127     0.224     0.162       925
           2      0.138     0.272     0.183      1033
           3      0.408     0.137     0.205      3958
           4      0.138     0.272     0.183      1033
           5      0.127     0.224     0.162       925
           6      0.181     0.132     0.153      1450

    accuracy                          0.177     10774
   macro avg      0.186     0.199     0.172     10774
weighted avg      0.247     0.177     0.180     10774

