Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix


Loading the Dataset

In [2]:
# Load data
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("val.csv")

# Prepare data - Handle conversion safely
X_train = train_df[[f"p{i}" for i in range(1, 43)] + ["turn"]]
y_train = train_df["label_move_col"]

X_val = val_df[[f"p{i}" for i in range(1, 43)] + ["turn"]]
y_val = val_df["label_move_col"]

# Convert to numeric and handle non-integer values
X_train = X_train.apply(pd.to_numeric, errors='coerce').fillna(0).astype("int")
y_train = pd.to_numeric(y_train, errors='coerce').fillna(0).astype("int")

X_val = X_val.apply(pd.to_numeric, errors='coerce').fillna(0).astype("int")
y_val = pd.to_numeric(y_val, errors='coerce').fillna(0).astype("int")


Decision Tree Model

In [3]:
# training Decision Tree 
Decision_tree = DecisionTreeClassifier(random_state=42, max_depth=15)
Decision_tree.fit(X_train, y_train)

# Prediction
y_pred = Decision_tree.predict(X_val)

# Results
accuracy = accuracy_score(y_val, y_pred)
cm = confusion_matrix(y_val, y_pred)

print(f" Decision Tree Accuracy: {accuracy:.4f}")
print(f" Confusion Matrix:")
print(cm)

 Decision Tree Accuracy: 0.4084
 Confusion Matrix:
[[ 480  112  118  313  129   92  206]
 [ 181  174   75  242   69   68  116]
 [ 192   64  263  235   84   56  139]
 [ 403  160  140 2686  150  121  298]
 [ 216   69   79  224  257   65  123]
 [ 170   65   76  217   68  200  129]
 [ 329  107  131  351  106   86  340]]
