In [2]:
# Import libraries
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load data
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("val.csv")

# Prepare data
X_train = train_df[[f"p{i}" for i in range(1, 43)] + ["turn"]]
y_train = train_df["label_move_col"]

X_val = val_df[[f"p{i}" for i in range(1, 43)] + ["turn"]]
y_val = val_df["label_move_col"]

# Convert to numeric safely
X_train = X_train.apply(pd.to_numeric, errors='coerce').fillna(0).astype("int")
y_train = pd.to_numeric(y_train, errors='coerce').fillna(0).astype("int")
X_val = X_val.apply(pd.to_numeric, errors='coerce').fillna(0).astype("int")
y_val = pd.to_numeric(y_val, errors='coerce').fillna(0).astype("int")

# XGBoost model
xgb_model = XGBClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=10,
    learning_rate=0.1,
    eval_metric='mlogloss'
)

xgb_model.fit(X_train, y_train)

# Predictions
xgb_pred = xgb_model.predict(X_val)

# Results
xgb_accuracy = accuracy_score(y_val, xgb_pred)
xgb_cm = confusion_matrix(y_val, xgb_pred)

print(f" XGBoost Accuracy: {xgb_accuracy:.4f}")
print(f" Confusion Matrix:")
print(xgb_cm)

 XGBoost Accuracy: 0.6120
 Confusion Matrix:
[[ 630   68   71  345   87   60  189]
 [  76  448   30  211   49   50   61]
 [  77   30  513  207   42   43  121]
 [ 170   58   47 3394   46   65  178]
 [ 117   37   46  205  524   27   77]
 [  62   41   41  208   33  467   73]
 [ 198   57   88  353   62   74  618]]
